force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/AvaliacaoEsportivaSocioemocional__c.object-meta.xml
<CustomObject>
    <label>Avaliação Esportiva e Socioemocional</label>
    <nameField>
        <displayFormat>AES-{00000000}</displayFormat>
        <label>Número AES</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avaliações Esportivas e Socioemocionais</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Nivel_Socioemocional__c.field-meta.xml
<CustomField>
    <fullName>Nivel_Socioemocional__c</fullName>
    <formula>IF(  NotaSocioemocionalA1__c  &lt; 13,
IMAGE(&quot;/servlet/servlet.FileDownload?file=015Z00000037TXB&quot;, &quot;green&quot;, 30, 30),
IF( NotaSocioemocionalA1__c &gt; 12 &amp;&amp; NotaSocioemocionalA1__c &lt; 30,
IMAGE(&quot;/servlet/servlet.FileDownload?file=015Z00000037TXG&quot;, &quot;yellow&quot;, 30, 30),
IF( NotaSocioemocionalA1__c &gt; 29 &amp;&amp; NotaSocioemocionalA1__c &lt; 47 ,
IMAGE(&quot;/servlet/servlet.FileDownload?file=015Z00000037TXL&quot;, &quot;orange&quot;, 30, 30),
IMAGE(&quot;/servlet/servlet.FileDownload?file=015Z00000037TXQ&quot;, &quot;blue&quot;, 30, 30)
)))</formula>
    <label>Nível Socioemocional</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/NivelEsportivoDoAluno__c.field-meta.xml
<CustomField>
    <fullName>NivelEsportivoDoAluno__c</fullName>
    <formula>NivelA3__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nível Esportivo do Aluno</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/recordTypes/Esportivo.recordType-meta.xml
<RecordType>
    <fullName>Esportivo</fullName>
    <active>true</active>
    <label>Esportivo</label>
</RecordType>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/recordTypes/Socioemocional.recordType-meta.xml
<RecordType>
    <fullName>Socioemocional</fullName>
    <active>true</active>
    <label>Socioemocional</label>
</RecordType>

force-app/main/default/classes/AvaliacaoAlunoBO.cls
public with sharing class AvaliacaoAlunoBO{
    public static AvaliacaoAlunoBO.AvaliacaoAnualTO avaliarAluno(String alunoId, String ano){
        AvaliacaoAlunoBO.AvaliacaoAnualTO retorno = new AvaliacaoAlunoBO.AvaliacaoAnualTO();

        List<AvaliacaoEsportivaSocioemocional__c> lstAvaliacoes = AvaliacaoEsportivaSocioemocionalDAO.getInstance().getByAluno(alunoId, ano);

        for (AvaliacaoEsportivaSocioemocional__c item : lstAvaliacoes) {
            if(Util.getRecordTypeId('AvaliacaoEsportivaSocioEmocional__c', 'Esportivo') == item.RecordTypeId){
                if(item.NivelEsportivoDoAluno__c.contains('green') || item.NivelEsportivoDoAluno__c.contains('Verde')){
                    retorno.ResultadoEsportiva = 'verde';
                }else if(item.NivelEsportivoDoAluno__c.contains('orange') || item.NivelEsportivoDoAluno__c.contains('Laranja')){
                    retorno.ResultadoEsportiva = 'laranja';
                }else if(item.NivelEsportivoDoAluno__c.contains('blue') || item.NivelEsportivoDoAluno__c.contains('Azul')){
                    retorno.ResultadoEsportiva = 'azul';
                }if(item.NivelEsportivoDoAluno__c.contains('yellow') || item.NivelEsportivoDoAluno__c.contains('Amarelo')){
                    retorno.ResultadoEsportiva = 'amarela';
                }        
            }else{
                if(Util.getRecordTypeId('AvaliacaoEsportivaSocioEmocional__c', 'Socioemocional') == item.RecordTypeId){
                    if(item.Nivel_Socioemocional__c.contains('green') || item.Nivel_Socioemocional__c.contains('Verde')){
                        retorno.ResultadoSocioemocional = 'verde';
                    }else if(item.Nivel_Socioemocional__c.contains('orange') || item.Nivel_Socioemocional__c.contains('Laranja')){
                        retorno.ResultadoSocioemocional = 'laranja';
                    }else if(item.Nivel_Socioemocional__c.contains('blue') || item.Nivel_Socioemocional__c.contains('Azul')){
                        retorno.ResultadoSocioemocional = 'azul';
                    }if(item.Nivel_Socioemocional__c.contains('yellow') || item.Nivel_Socioemocional__c.contains('Amarelo')){
                        retorno.ResultadoSocioemocional = 'amarela';
                    }     
                }
            }
        }

        return retorno;
    }

    public class AvaliacaoAnualTO{
        @AuraEnabled
        public String ResultadoEsportiva {get; set;}
        @AuraEnabled
        public String ResultadoSocioemocional {get; set;}
    }

}