force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/AvaliacaoEsportivaSocioemocional__c.object-meta.xml
<CustomObject>
    <label>Avaliação Esportiva e Socioemocional</label>
    <nameField>
        <displayFormat>AES-{00000000}</displayFormat>
        <label>Número AES</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avaliações Esportivas e Socioemocionais</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Aluno__c.field-meta.xml
<CustomField>
    <fullName>Aluno__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Aluno</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aluno</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Avaliações Esportivas e Socioemocionais</relationshipLabel>
    <relationshipName>Avaliacoes_Esportivas_e_Socioemocionais</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/AnoBaseEsportivo__c.field-meta.xml
<CustomField>
    <fullName>AnoBaseEsportivo__c</fullName>
    <label>Ano Base Esportivo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/AtacanteComBolaA3__c.field-meta.xml
<CustomField>
    <fullName>AtacanteComBolaA3__c</fullName>
    <label>Atacante com bola A3</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/AtacanteSemBolaA3__c.field-meta.xml
<CustomField>
    <fullName>AtacanteSemBolaA3__c</fullName>
    <label>Atacante sem bola A3</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Autoconfianca__c.field-meta.xml
<CustomField>
    <fullName>Autoconfianca__c</fullName>
    <label>Autoconfiança</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Autocontrole__c.field-meta.xml
<CustomField>
    <fullName>Autocontrole__c</fullName>
    <label>Autocontrole</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Autonomia__c.field-meta.xml
<CustomField>
    <fullName>Autonomia__c</fullName>
    <label>Autonomia</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Comunicacao__c.field-meta.xml
<CustomField>
    <fullName>Comunicacao__c</fullName>
    <label>Comunicação</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/ConceitosOfensivoseDefensivosA3__c.field-meta.xml
<CustomField>
    <fullName>ConceitosOfensivoseDefensivosA3__c</fullName>
    <label>Conceitos ofensivos e defensivos A3</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Cooperacao__c.field-meta.xml
<CustomField>
    <fullName>Cooperacao__c</fullName>
    <label>Cooperação</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/DefensorForaDaBolaA3__c.field-meta.xml
<CustomField>
    <fullName>DefensorForaDaBolaA3__c</fullName>
    <label>Defensor(a) fora da bola A3</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/DefensorNaBolaA3__c.field-meta.xml
<CustomField>
    <fullName>DefensorNaBolaA3__c</fullName>
    <label>Defensor(a) na bola A3</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Empatia__c.field-meta.xml
<CustomField>
    <fullName>Empatia__c</fullName>
    <label>Empatia</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Honestidade__c.field-meta.xml
<CustomField>
    <fullName>Honestidade__c</fullName>
    <label>Honestidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Periodo_de_Avaliacao__c.field-meta.xml
<CustomField>
    <fullName>Periodo_de_Avaliacao__c</fullName>
    <label>Período de Avaliação</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1ª Avaliação</fullName>
            </value>
            <value>
                <fullName>2ª Avaliação</fullName>
            </value>
            <value>
                <fullName>3ª Avaliação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Persistencia__c.field-meta.xml
<CustomField>
    <fullName>Persistencia__c</fullName>
    <label>Persistência</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Resiliencia__c.field-meta.xml
<CustomField>
    <fullName>Resiliencia__c</fullName>
    <label>Resiliência</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Respeito__c.field-meta.xml
<CustomField>
    <fullName>Respeito__c</fullName>
    <label>Respeito</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Responsabilidade__c.field-meta.xml
<CustomField>
    <fullName>Responsabilidade__c</fullName>
    <label>Responsabilidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/TecnicaIndividualA3__c.field-meta.xml
<CustomField>
    <fullName>TecnicaIndividualA3__c</fullName>
    <label>Técnica Individual A3</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Tipo_de_Avaliacao__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Avaliacao__c</fullName>
    <label>Tipo de Avaliação</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diagnóstica</fullName>
            </value>
            <value>
                <fullName>Formativa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Tomada_de_decisao__c.field-meta.xml
<CustomField>
    <fullName>Tomada_de_decisao__c</fullName>
    <label>Tomada de decisão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Turma__c.field-meta.xml
<CustomField>
    <fullName>Turma__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Turma</label>
    <referenceTo>Turma__c</referenceTo>
    <relationshipLabel>Avaliações Esportivas e Socioemocionais</relationshipLabel>
    <relationshipName>Avaliacoes_Esportivas_e_Socioemocionais</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/recordTypes/Esportivo.recordType-meta.xml
<RecordType>
    <fullName>Esportivo</fullName>
    <active>true</active>
    <label>Esportivo</label>
</RecordType>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/recordTypes/Socioemocional.recordType-meta.xml
<RecordType>
    <fullName>Socioemocional</fullName>
    <active>true</active>
    <label>Socioemocional</label>
</RecordType>

force-app/main/default/objects/Turma__c/Turma__c.object-meta.xml
<CustomObject>
    <label>Turma</label>
    <nameField>
        <label>Nome da Turma</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Turmas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Turma__c/fields/Aluno__c.field-meta.xml
<CustomField>
    <fullName>Aluno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aluno</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Alunos</relationshipLabel>
    <relationshipName>Turmas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AvaliacaoAlunoControllerTest.cls
@IsTest
public class AvaliacaoAlunoControllerTest {
    @IsTest
    static void avaliarAlunoVerde(){
        Account objEscola = TestDataFactory.criarEscola('Escola teste');
        Contact objTreinador = TestDataFactory.criarTreinador('Fitzz');
        Turma__c objTurma = TestDataFactory.criarTurma('turma teste', objTreinador.Id, objEscola.Id);
        Contact objAluno = TestDataFactory.criarAluno('Aluno', objTurma.Id);

        AvaliacaoEsportivaSocioemocional__c objAvaliacaoEsportiva = new AvaliacaoEsportivaSocioemocional__c(
            Turma__c=objTurma.Id, 
            Aluno__c=objAluno.Id, 
            Tipo_de_Avaliacao__c='Diagnóstica',
            RecordTypeId = Util.getRecordTypeId('AvaliacaoEsportivaSocioEmocional__c', 'Esportivo'),
            DefensorNaBolaA3__c  = 1,
            DefensorForaDaBolaA3__c   = 1,
            ConceitosOfensivoseDefensivosA3__c  = 1,
            AtacanteComBolaA3__c   = 1,
            AtacanteSemBolaA3__c   = 1,
            TecnicaIndividualA3__c  = 1,
            AnoBaseEsportivo__c = '2022',
            Periodo_de_Avaliacao__c = '1ª Avaliação'
        );
        insert objAvaliacaoEsportiva;

        AvaliacaoEsportivaSocioemocional__c objAvaliacaoSocioEmocional = new AvaliacaoEsportivaSocioemocional__c(
            Turma__c=objTurma.Id, 
            Aluno__c=objAluno.Id, 
            Tipo_de_Avaliacao__c='Diagnóstica',
            RecordTypeId = Util.getRecordTypeId('AvaliacaoEsportivaSocioEmocional__c', 'Socioemocional'),
            Autoconfianca__c = 1,
            Empatia__c = 1,
            Honestidade__c = 1,
            Respeito__c = 1,
            Autonomia__c = 1,
            Responsabilidade__c = 1,
            Autocontrole__c  = 1,
            Tomada_de_decisao__c = 1,
            Comunicacao__c  = 1,
            Cooperacao__c = 1,
            Persistencia__c  = 1,
            Resiliencia__c = 1,
            AnoBaseEsportivo__c = '2022',
            Periodo_de_Avaliacao__c = '1ª Avaliação'
        );

        insert objAvaliacaoSocioEmocional;

        Test.startTest();
        AvaliacaoAlunoBO.AvaliacaoAnualTO retorno = AvaliacaoAlunoController.avaliarAluno(objAluno.Id, '2022');
        Test.stopTest();

        System.assertEquals('verde', retorno.ResultadoEsportiva);
        System.assertEquals('azul', retorno.ResultadoSocioemocional);
    }

    @IsTest
    static void avaliarAlunoLaranja(){
        Account objEscola = TestDataFactory.criarEscola('Escola teste');
        Contact objTreinador = TestDataFactory.criarTreinador('Fitzz');
        Turma__c objTurma = TestDataFactory.criarTurma('turma teste', objTreinador.Id, objEscola.Id);
        Contact objAluno = TestDataFactory.criarAluno('Aluno', objTurma.Id);

        AvaliacaoEsportivaSocioemocional__c objAvaliacaoEsportiva = new AvaliacaoEsportivaSocioemocional__c(
            Turma__c=objTurma.Id, 
            Aluno__c=objAluno.Id, 
            Tipo_de_Avaliacao__c='Diagnóstica',
            RecordTypeId = Util.getRecordTypeId('AvaliacaoEsportivaSocioEmocional__c', 'Esportivo'),
            DefensorNaBolaA3__c  = 50,
            DefensorForaDaBolaA3__c  = 50,
            ConceitosOfensivoseDefensivosA3__c  = 50,
            AtacanteComBolaA3__c   = 50,
            AtacanteSemBolaA3__c   = 50,
            TecnicaIndividualA3__c  = 50,
            AnoBaseEsportivo__c = '2022',
            Periodo_de_Avaliacao__c = '1ª Avaliação'
        );
        insert objAvaliacaoEsportiva;

        AvaliacaoEsportivaSocioemocional__c objAvaliacaoSocioEmocional = new AvaliacaoEsportivaSocioemocional__c(
            Turma__c=objTurma.Id, 
            Aluno__c=objAluno.Id, 
            Tipo_de_Avaliacao__c='Diagnóstica',
            RecordTypeId = Util.getRecordTypeId('AvaliacaoEsportivaSocioEmocional__c', 'Socioemocional'),
            Autoconfianca__c = 5,
            Empatia__c = 3,
            Honestidade__c = 8,
            Respeito__c = 8,
            Autonomia__c = 4,
            Responsabilidade__c = 6,
            Autocontrole__c  = 7,
            Tomada_de_decisao__c = 6,
            Comunicacao__c  = 4,
            Cooperacao__c = 5,
            Persistencia__c  = 5,
            Resiliencia__c = 7,
            AnoBaseEsportivo__c = '2022',
            Periodo_de_Avaliacao__c = '1ª Avaliação'
        );

        insert objAvaliacaoSocioEmocional;

        Test.startTest();
        AvaliacaoAlunoBO.AvaliacaoAnualTO retorno = AvaliacaoAlunoController.avaliarAluno(objAluno.Id, '2022');
        Test.stopTest();

        System.assertEquals('azul', retorno.ResultadoEsportiva);
    }
}