force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/AvaliacaoEsportivaSocioemocional__c.object-meta.xml
<CustomObject>
    <label>Avaliação Esportiva e Socioemocional</label>
    <nameField>
        <displayFormat>AES-{00000000}</displayFormat>
        <label>Número AES</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avaliações Esportivas e Socioemocionais</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Aluno__c.field-meta.xml
<CustomField>
    <fullName>Aluno__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Aluno</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Aluno</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Avaliações Esportivas e Socioemocionais</relationshipLabel>
    <relationshipName>Avaliacoes_Esportivas_e_Socioemocionais</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Ano_Base_Socioemocional__c.field-meta.xml
<CustomField>
    <fullName>Ano_Base_Socioemocional__c</fullName>
    <label>Ano Base Socioemocional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/AnoBaseEsportivo__c.field-meta.xml
<CustomField>
    <fullName>AnoBaseEsportivo__c</fullName>
    <label>Ano Base Esportivo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/Nivel_Socioemocional__c.field-meta.xml
<CustomField>
    <fullName>Nivel_Socioemocional__c</fullName>
    <formula>IF(  NotaSocioemocionalA1__c  &lt; 13,
IMAGE(&quot;/servlet/servlet.FileDownload?file=015Z00000037TXB&quot;, &quot;green&quot;, 30, 30),
IF( NotaSocioemocionalA1__c &gt; 12 &amp;&amp; NotaSocioemocionalA1__c &lt; 30,
IMAGE(&quot;/servlet/servlet.FileDownload?file=015Z00000037TXG&quot;, &quot;yellow&quot;, 30, 30),
IF( NotaSocioemocionalA1__c &gt; 29 &amp;&amp; NotaSocioemocionalA1__c &lt; 47 ,
IMAGE(&quot;/servlet/servlet.FileDownload?file=015Z00000037TXL&quot;, &quot;orange&quot;, 30, 30),
IMAGE(&quot;/servlet/servlet.FileDownload?file=015Z00000037TXQ&quot;, &quot;blue&quot;, 30, 30)
)))</formula>
    <label>Nível Socioemocional</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AvaliacaoEsportivaSocioemocional__c/fields/NivelEsportivoDoAluno__c.field-meta.xml
<CustomField>
    <fullName>NivelEsportivoDoAluno__c</fullName>
    <formula>NivelA3__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nível Esportivo do Aluno</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AvaliacaoEsportivaSocioemocionalDAO.cls
public with sharing class AvaliacaoEsportivaSocioemocionalDAO {
    private static final AvaliacaoEsportivaSocioemocionalDAO instance = new AvaliacaoEsportivaSocioemocionalDAO();

    public static AvaliacaoEsportivaSocioemocionalDAO getInstance(){
        return instance;
    }

    public List<AvaliacaoEsportivaSocioEmocional__c> getByAluno(Id pIdAluno, String pAnoBase) 
    {
        return [
            SELECT 
                Id,
                Aluno__c,
                Ano_Base_Socioemocional__c,
                AnoBaseEsportivo__c,
                Nivel_Socioemocional__c,
                NivelEsportivoDoAluno__c,
                RecordTypeId
            FROM 
                AvaliacaoEsportivaSocioEmocional__c 
            WHERE 
                Aluno__c = :pIdAluno 
            AND (Ano_Base_Socioemocional__c = :pAnoBase OR AnoBaseEsportivo__c = :pAnoBase)
        ];
    }
}