force-app/main/default/objects/GradeHoraria__c/GradeHoraria__c.object-meta.xml
<CustomObject>
    <label>Grade horária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades horárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GradeHoraria__c/fields/Local__c.field-meta.xml
<CustomField>
    <fullName>Local__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grades horárias</relationshipLabel>
    <relationshipName>GradesHorarias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GradeHorariaDAO.cls
public without sharing class GradeHorariaDAO {
    private static final GradeHorariaDAO instance = new GradeHorariaDAO();

    public static GradeHorariaDAO getInstance(){
        return instance;
    }

    public GradeHoraria__c getById(Id pId){
        return [
                SELECT 
                    Id, 
                    Local__c 
                FROM 
                    GradeHoraria__c 
                WHERE 
                    Id = :pId];
    }
}