force-app/main/default/objects/GradeHoraria__c/GradeHoraria__c.object-meta.xml
<CustomObject>
    <label>Grade horária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades horárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GradeHoraria__c/fields/DiaTreino__c.field-meta.xml
<CustomField>
    <fullName>DiaTreino__c</fullName>
    <label>Dia de treino</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Segunda-feira</fullName>
            </value>
            <value>
                <fullName>Terça-feira</fullName>
            </value>
            <value>
                <fullName>Quarta-feira</fullName>
            </value>
            <value>
                <fullName>Quinta-feira</fullName>
            </value>
            <value>
                <fullName>Sexta-feira</fullName>
            </value>
            <value>
                <fullName>Sábado</fullName>
            </value>
            <value>
                <fullName>Domingo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GradeHoraria__c/fields/NomeTurma__c.field-meta.xml
<CustomField>
    <fullName>NomeTurma__c</fullName>
    <label>Nome da turma</label>
    <referenceTo>Turma__c</referenceTo>
    <relationshipLabel>Grade horária</relationshipLabel>
    <relationshipName>GradesHorarias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Turma__c/Turma__c.object-meta.xml
<CustomObject>
    <label>Turma</label>
    <nameField>
        <label>Nome da Turma</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Turmas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Turma__c/fields/NomeEscola__c.field-meta.xml
<CustomField>
    <fullName>NomeEscola__c</fullName>
    <label>Nome da escola</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Turmas</relationshipLabel>
    <relationshipName>Turmas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Turma__c/fields/SexoTurma__c.field-meta.xml
<CustomField>
    <fullName>SexoTurma__c</fullName>
    <label>Sexo da turma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Feminino</fullName>
            </value>
            <value>
                <fullName>Mista</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Turma__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GradeHorariaControllerTest.cls
@isTest
public class GradeHorariaControllerTest {
    @IsTest
    static void testandoSalvarGrade(){

        Account objEscola = new Account(Name = 'Supera', Numero__c = '123', NomeResponsavelEntidade__c = 'José', Site = 'Teste', NumberOfEmployees = 23, Type = 'Estadual');
        insert objEscola;

        //Setup - cria turma
        Turma__c turma = new Turma__c(NomeEscola__c = objEscola.Id, Name = 'Superação', SexoTurma__c = 'Mista', Status__c = 'Ativo');
        insert turma;

        GradeHoraria__c grade1 = new GradeHoraria__c(NomeTurma__c = turma.Id, DiaTreino__c = 'Segunda-feira');
        insert grade1;

        Test.startTest();
        Boolean retorno = GradeHorariaController.salvar(grade1.Id, objEscola.Id);
        Test.stopTest();

        System.assertEquals(true, retorno);
    }

    @IsTest
    static void testandoSalvarAccount(){
        Id recTreinador = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('TreinadorTutor').getRecordTypeId();

        Account objEscola = new Account(Name = 'Supera', Numero__c = '123', NomeResponsavelEntidade__c = 'José', Site = 'Teste', NumberOfEmployees = 23, Type = 'Estadual');
        insert objEscola;

        //Setup - cria treinador1
        Contact contato = new Contact(FirstName = 'Tulio', LastName = 'Malaquias', RecordTypeId = recTreinador, AccountId = objEscola.Id, MailingStreet = 'teste');
        insert contato;

        //Setup - cria turma
        Turma__c turma = new Turma__c(NomeEscola__c = objEscola.Id, Name = 'Superação', SexoTurma__c = 'Mista', Status__c = 'Ativo');
        insert turma;

        GradeHoraria__c grade1 = new GradeHoraria__c(NomeTurma__c = turma.Id, DiaTreino__c = 'Segunda-feira');
        insert grade1;

        Test.startTest();
        Boolean retorno = GradeHorariaController.salvar(contato.Id, objEscola.Id);
        Test.stopTest();

        System.assertEquals(true, retorno);
    }

    @IsTest
    static void testandoSalvarGradeErro(){

        Test.startTest();
        Boolean retorno = GradeHorariaController.salvar(null, null);
        Test.stopTest();

        System.assertEquals(false, retorno);
    }
}