force-app/main/default/objects/GradeHoraria__c/GradeHoraria__c.object-meta.xml
<CustomObject>
    <label>Grade horária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades horárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GradeHoraria__c/fields/Local__c.field-meta.xml
<CustomField>
    <fullName>Local__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Grades horárias</relationshipLabel>
    <relationshipName>GradesHorarias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GradeHorariaController.cls
public without sharing class GradeHorariaController {
    @AuraEnabled
    public static Boolean salvar(String recordId, String recordAccount){
        try {
            Account objAccount = AccountDAO.getInstance().getById(recordAccount);

            if(recordId.startsWith('a02')){
                GradeHoraria__c objGradeHoraria = GradeHorariaDAO.getInstance().getById(recordId);
                objGradeHoraria.Local__c = objAccount.Id;
                update objGradeHoraria;
            }else{
                Contact objContact = contactDAO.getById(recordId);
                objContact.AccountId = recordAccount;
                update objContact;
            }
            
            return true;
        } catch (Exception ex) {
            return false;
        }
    }
}