force-app/main/default/objects/Chamada__c/Chamada__c.object-meta.xml
<CustomObject>
    <label>Chamada</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chamadas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Chamada__c/fields/Aluno__c.field-meta.xml
<CustomField>
    <fullName>Aluno__c</fullName>
    <label>Aluno</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Chamadas</relationshipLabel>
    <relationshipName>Chamadas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Chamada__c/fields/Ano__c.field-meta.xml
<CustomField>
    <fullName>Ano__c</fullName>
    <label>Ano</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chamada__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Atestado</fullName>
            </value>
            <value>
                <fullName>Ausente</fullName>
            </value>
            <value>
                <fullName>Feriado</fullName>
            </value>
            <value>
                <fullName>Férias</fullName>
            </value>
            <value>
                <fullName>Folga</fullName>
            </value>
            <value>
                <fullName>Jogo</fullName>
            </value>
            <value>
                <fullName>Presente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chamada__c/fields/Treinador__c.field-meta.xml
<CustomField>
    <fullName>Treinador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treinador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Treinador/Tutor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Treinador</relationshipLabel>
    <relationshipName>Treinador</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chamada__c/fields/Turma__c.field-meta.xml
<CustomField>
    <fullName>Turma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Turma</label>
    <referenceTo>Turma__c</referenceTo>
    <relationshipLabel>Chamadas</relationshipLabel>
    <relationshipName>Chamadas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Turma__c/Turma__c.object-meta.xml
<CustomObject>
    <label>Turma</label>
    <nameField>
        <label>Nome da Turma</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Turmas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Turma__c/fields/Aluno__c.field-meta.xml
<CustomField>
    <fullName>Aluno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aluno</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Alunos</relationshipLabel>
    <relationshipName>Turmas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Turma__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Turma__c/fields/Treinador__c.field-meta.xml
<CustomField>
    <fullName>Treinador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treinador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Turmas</relationshipLabel>
    <relationshipName>TreinadorTurma</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/listaDePresencaController.cls
public with sharing class listaDePresencaController {
    
    @AuraEnabled
    public static void saveListaDePresenca(String statusPresenca, String alunoId, String data, String dia, String mes, String ano, String turma){
        Map<String, Chamada__c> mapInicial = buscarChamadaMap(turma, dia, mes, ano);
		String treinador = returnTreinador(turma);
		System.debug(alunoId);
        try {
            data = dia + '/' + mes + '/' + ano;
            Date dataFormatada = Date.parse(data);
            Map<String, String> statusPresencaMap = (Map<String, String>) JSON.deserialize(statusPresenca, Map<String, String>.class);
            Map<String, String> alunoMap = (Map<String, String>) JSON.deserialize(alunoId, Map<String, String>.class);

            if(mapInicial.isEmpty()){
                for(String statusId : statusPresencaMap.keySet()){
                    criarChamada(statusPresencaMap.get(statusId), alunoMap.get(statusId), dataFormatada, ano, turma, treinador);
                }
            } else{ 
                for(String statusId : statusPresencaMap.keySet()){
                    if(mapInicial.get(statusId) != null){
                        mapInicial.get(statusId).Status__c = statusPresencaMap.get(statusId);
                        mapInicial.get(statusId).Data__c = dataFormatada;
                        mapInicial.get(statusId).Ano__c = ano;
                    } else{
                        criarChamada(statusPresencaMap.get(statusId), alunoMap.get(statusId), dataFormatada, ano, turma, treinador);
                    }
                }    
                update mapInicial.values();
            }
            
        }
        catch (DmlException e) {
            System.debug(e.getMessage());
        }
    }

    @AuraEnabled
    public static Map<String, Chamada__c> buscarChamadaMap(String turma, String dia, String mes, String ano){
        Map<String, Chamada__c> mapChamada = new Map<String, Chamada__c>();

        String data = dia + '/' + mes + '/' + ano;
        Date dataFormat = Date.parse(data);

        for(Chamada__c chamada : [SELECT Id, Data__c, Status__c, Turma__c, Aluno__c, Treinador__c FROM Chamada__c WHERE Data__c = :dataFormat AND Turma__c = :turma]){
            mapChamada.put(chamada.Aluno__c, chamada);
        }
        
        return mapChamada;
    }

    @AuraEnabled
    public static List<Chamada__c> buscarChamadaList(String turma, String dia, String mes, String ano){

        String data = dia + '/' + mes + '/' + ano;
        Date dataFormat = Date.parse(data);

        return[
            SELECT 
            Id, 
            Data__c,
            Status__c,
            Turma__c,
            Aluno__c,
            Treinador__c
                FROM Chamada__c
                WHERE Data__c = :dataFormat AND Turma__c = :turma
        ];
    }

    @AuraEnabled
    public static void criarChamada(String status, String aluno, Date data, String ano, String turma, String treinador){
        Chamada__c listChamada = new Chamada__c();

        listChamada.Status__c = status;
        listChamada.Aluno__c = aluno;
        listChamada.Data__c = data;
        listChamada.Ano__c = ano;
        listChamada.Turma__c = turma;
        listChamada.Treinador__c = treinador;
        
        insert listChamada;
    }
	
	@AuraEnabled
	public static Id returnTreinador(String turma){
		Id idTreinador = [SELECT Id, Treinador__c FROM Turma__c WHERE Id = :turma].Treinador__c;
		return idTreinador;
	}
}