force-app/main/default/objects/Chamada__c/Chamada__c.object-meta.xml
<CustomObject>
    <label>Chamada</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chamadas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Chamada__c/fields/Aluno__c.field-meta.xml
<CustomField>
    <fullName>Aluno__c</fullName>
    <label>Aluno</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Chamadas</relationshipLabel>
    <relationshipName>Chamadas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Chamada__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Atestado</fullName>
            </value>
            <value>
                <fullName>Ausente</fullName>
            </value>
            <value>
                <fullName>Feriado</fullName>
            </value>
            <value>
                <fullName>Férias</fullName>
            </value>
            <value>
                <fullName>Folga</fullName>
            </value>
            <value>
                <fullName>Jogo</fullName>
            </value>
            <value>
                <fullName>Presente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chamada__c/fields/Turma__c.field-meta.xml
<CustomField>
    <fullName>Turma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Turma</label>
    <referenceTo>Turma__c</referenceTo>
    <relationshipLabel>Chamadas</relationshipLabel>
    <relationshipName>Chamadas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GradeHoraria__c/GradeHoraria__c.object-meta.xml
<CustomObject>
    <label>Grade horária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades horárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GradeHoraria__c/fields/DiaTreino__c.field-meta.xml
<CustomField>
    <fullName>DiaTreino__c</fullName>
    <label>Dia de treino</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Segunda-feira</fullName>
            </value>
            <value>
                <fullName>Terça-feira</fullName>
            </value>
            <value>
                <fullName>Quarta-feira</fullName>
            </value>
            <value>
                <fullName>Quinta-feira</fullName>
            </value>
            <value>
                <fullName>Sexta-feira</fullName>
            </value>
            <value>
                <fullName>Sábado</fullName>
            </value>
            <value>
                <fullName>Domingo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GradeHoraria__c/fields/NomeTurma__c.field-meta.xml
<CustomField>
    <fullName>NomeTurma__c</fullName>
    <label>Nome da turma</label>
    <referenceTo>Turma__c</referenceTo>
    <relationshipLabel>Grade horária</relationshipLabel>
    <relationshipName>GradesHorarias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Turma__c/Turma__c.object-meta.xml
<CustomObject>
    <label>Turma</label>
    <nameField>
        <label>Nome da Turma</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Turmas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Turma__c/fields/Aluno__c.field-meta.xml
<CustomField>
    <fullName>Aluno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aluno</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Alunos</relationshipLabel>
    <relationshipName>Turmas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Turma__c/fields/NomeEscola__c.field-meta.xml
<CustomField>
    <fullName>NomeEscola__c</fullName>
    <label>Nome da escola</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Turmas</relationshipLabel>
    <relationshipName>Turmas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Turma__c/fields/SexoTurma__c.field-meta.xml
<CustomField>
    <fullName>SexoTurma__c</fullName>
    <label>Sexo da turma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Feminino</fullName>
            </value>
            <value>
                <fullName>Mista</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Turma__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/listaDePresencaControllerTest.cls
@IsTest
public with sharing class listaDePresencaControllerTest {
    @TestSetup static void testarMetodosDePresenca(){
        Id recAluno = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Aluno').getRecordTypeId();
        Id recTreinador = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('TreinadorTutor').getRecordTypeId();

        Account objEscola = new Account(Name = 'Supera', Numero__c = '123', NomeResponsavelEntidade__c = 'José', Site = 'Teste', NumberOfEmployees = 23, Type = 'Estadual');
        insert objEscola;

        System.debug('1');

        Contact objTreinador = new Contact(FirstName = 'Tulio', LastName = 'Malaquias', Cpf__c = '70189814098',  RecordTypeId = recTreinador, AccountId = objEscola.Id, MailingStreet = 'teste', PapelEquipe__c = 'Treinador');
        insert objTreinador;
        System.debug('2');

        Turma__c objTurma = new Turma__c(NomeEscola__c = objEscola.Id, Name = 'Superação', SexoTurma__c = 'Mista', Status__c = 'Ativo');
        insert objTurma;

        System.debug('3');

        List<GradeHoraria__c> lstGrade = new List<GradeHoraria__c>();
        lstGrade.add(
            new GradeHoraria__c(NomeTurma__c = objTurma.Id, DiaTreino__c = 'Segunda-feira')
        );
        lstGrade.add(
            new GradeHoraria__c(NomeTurma__c = objTurma.Id, DiaTreino__c = 'Terça-feira')
        );
        lstGrade.add(
            new GradeHoraria__c(NomeTurma__c = objTurma.Id, DiaTreino__c = 'Quarta-feira')
        );
        lstGrade.add(
            new GradeHoraria__c(NomeTurma__c = objTurma.Id, DiaTreino__c = 'Sábado')
        );

        insert lstGrade;

        
        System.debug('4');

        List<Contact> lstAlunos = new List<Contact>();
        lstAlunos.add(
            new Contact(FirstName = 'Flavio', LastName = 'Spedo', RecordTypeId = recAluno, Turma__c = objTurma.Id, AccountId = objEscola.Id, MailingStreet = 'teste')
        );

        lstAlunos.add(
            new Contact(FirstName = 'Igor', LastName = 'Rangel', RecordTypeId = recAluno, Turma__c = objTurma.Id, AccountId = objEscola.Id, MailingStreet = 'teste')
        );

        lstAlunos.add(
            new Contact(FirstName = 'Maria', LastName = 'Conceição', RecordTypeId = recAluno, Turma__c = objTurma.Id, AccountId = objEscola.Id, MailingStreet = 'teste')
        );

        insert lstAlunos;

        
        System.debug('5');

        List<Chamada__c> lstChamada = new List<Chamada__c>();
        lstChamada.add(
            new Chamada__c(Data__c = Date.newInstance(2021, 10, 04), Status__c = 'Presente', Turma__c = objTurma.Id, Aluno__c = lstAlunos[0].Id)    
        );

        lstChamada.add(
            new Chamada__c(Data__c = Date.newInstance(2021, 10, 04), Status__c = 'Presente', Turma__c = objTurma.Id, Aluno__c = lstAlunos[1].Id)
        );

        lstChamada.add(
            new Chamada__c(Data__c = Date.newInstance(2021, 10, 04), Status__c = 'Presente', Turma__c = objTurma.Id, Aluno__c = lstAlunos[2].Id)
        );

        insert lstChamada;

        
        System.debug('6');
    }

    @IsTest
    static void testandoSalvarListaDePresenca(){
        Id recAluno = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Aluno').getRecordTypeId();
        List<Contact> lstContact = [SELECT Id FROM Contact WHERE RecordTypeId = :recAluno]; 
        List<Turma__c> lstTurma = [SELECT Id FROM Turma__c]; 

        String presencasMap = '{"'+lstContact[0].Id+'":"Presente","'+lstContact[1].Id+'":"Falta","'+lstContact[2].Id+'":"Atestado"}';
        String alunosMap = '{"'+lstContact[0].Id+'":"'+lstContact[0].Id+'","'+lstContact[1].Id+'":"'+lstContact[1].Id+'","'+lstContact[2].Id+'":"'+lstContact[2].Id+'"}';

        Test.startTest();
        listaDePresencaController.saveListaDePresenca(presencasMap, alunosMap, '', '06', '01', '2022', lstTurma[0].Id);
        Test.stopTest();

        Date dataChamada = Date.newInstance(2022, 01, 06);
        List<Chamada__c> lstChamada = [SELECT Id, Data__c FROM Chamada__c WHERE Data__c = :dataChamada];

        System.assertNotEquals(null, lstChamada);
    }

    @IsTest
    static void testandoSalvarListaDePresencaSemDadosIniciais(){
        Id recAluno = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Aluno').getRecordTypeId();
        List<Contact> lstContact = [SELECT Id FROM Contact WHERE RecordTypeId = :recAluno]; 
        List<Turma__c> lstTurma = [SELECT Id FROM Turma__c]; 
        

        String presencasMap = '{"'+lstContact[0].Id+'":"Presente","'+lstContact[1].Id+'":"Falta","'+lstContact[2].Id+'":"Atestado"}';
        String alunosMap = '{"'+lstContact[0].Id+'":"'+lstContact[0].Id+'","'+lstContact[1].Id+'":"'+lstContact[1].Id+'","'+lstContact[2].Id+'":"'+lstContact[2].Id+'"}';

        Test.startTest();
        listaDePresencaController.saveListaDePresenca(presencasMap, alunosMap, '', '04', '10', '2021', lstTurma[0].Id);
        Test.stopTest();

        Date dataChamada = Date.newInstance(2022, 01, 06);
        List<Chamada__c> lstChamada = [SELECT Id, Data__c FROM Chamada__c WHERE Data__c = :dataChamada];

        System.assertNotEquals(null, lstChamada);
    }

    @IsTest
    static void testandoBuscarChamada(){
        List<Turma__c> lstTurma = [SELECT Id FROM Turma__c];
        
        Test.startTest();
		Map<String, Chamada__c> objRetorno = listaDePresencaController.buscarChamadaMap(lstTurma[0].Id, '04', '10', '2021');
		Test.stopTest();

        System.debug(objRetorno);

        System.assertNotEquals(null, objRetorno);
    }

    @IsTest
    static void testandoBuscarChamadaLista()
    {
        List<Turma__c> lstTurma = [SELECT Id FROM Turma__c];

        Test.startTest();
        List<Chamada__c> listaChamada = listaDePresencaController.buscarChamadaList(lstTurma[0].Id, '04', '10', '2021');
        Test.stopTest();

        System.assertNotEquals(null, listaChamada);
    }
}