force-app/main/default/objects/Chamada__c/Chamada__c.object-meta.xml
<CustomObject>
    <label>Chamada</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chamadas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Chamada__c/fields/Aluno__c.field-meta.xml
<CustomField>
    <fullName>Aluno__c</fullName>
    <label>Aluno</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Chamadas</relationshipLabel>
    <relationshipName>Chamadas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Chamada__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Atestado</fullName>
            </value>
            <value>
                <fullName>Ausente</fullName>
            </value>
            <value>
                <fullName>Feriado</fullName>
            </value>
            <value>
                <fullName>Férias</fullName>
            </value>
            <value>
                <fullName>Folga</fullName>
            </value>
            <value>
                <fullName>Jogo</fullName>
            </value>
            <value>
                <fullName>Presente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chamada__c/fields/Treinador__c.field-meta.xml
<CustomField>
    <fullName>Treinador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treinador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Treinador/Tutor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Treinador</relationshipLabel>
    <relationshipName>Treinador</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chamada__c/fields/Turma__c.field-meta.xml
<CustomField>
    <fullName>Turma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Turma</label>
    <referenceTo>Turma__c</referenceTo>
    <relationshipLabel>Chamadas</relationshipLabel>
    <relationshipName>Chamadas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GradeHoraria__c/GradeHoraria__c.object-meta.xml
<CustomObject>
    <label>Grade horária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades horárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GradeHoraria__c/fields/DiaTreino__c.field-meta.xml
<CustomField>
    <fullName>DiaTreino__c</fullName>
    <label>Dia de treino</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Segunda-feira</fullName>
            </value>
            <value>
                <fullName>Terça-feira</fullName>
            </value>
            <value>
                <fullName>Quarta-feira</fullName>
            </value>
            <value>
                <fullName>Quinta-feira</fullName>
            </value>
            <value>
                <fullName>Sexta-feira</fullName>
            </value>
            <value>
                <fullName>Sábado</fullName>
            </value>
            <value>
                <fullName>Domingo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GradeHoraria__c/fields/HoraInicio__c.field-meta.xml
<CustomField>
    <fullName>HoraInicio__c</fullName>
    <label>Hora de início</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/GradeHoraria__c/fields/NomeTurma__c.field-meta.xml
<CustomField>
    <fullName>NomeTurma__c</fullName>
    <label>Nome da turma</label>
    <referenceTo>Turma__c</referenceTo>
    <relationshipLabel>Grade horária</relationshipLabel>
    <relationshipName>GradesHorarias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Turma__c/Turma__c.object-meta.xml
<CustomObject>
    <label>Turma</label>
    <nameField>
        <label>Nome da Turma</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Turmas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Turma__c/fields/Aluno__c.field-meta.xml
<CustomField>
    <fullName>Aluno__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aluno</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Alunos</relationshipLabel>
    <relationshipName>Turmas1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Turma__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Turma__c/fields/Treinador__c.field-meta.xml
<CustomField>
    <fullName>Treinador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treinador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Turmas</relationshipLabel>
    <relationshipName>TreinadorTurma</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PorcentagemPresencaControllerTest.cls
@IsTest
public class PorcentagemPresencaControllerTest {
    @TestSetup
    static void makeData(){
        Account escola = TestDataFactory.criarEscola('Escola teste');
        Contact treinador = TestDataFactory.criarTreinador('Fitzz');
        Turma__c turma = TestDataFactory.criarTurma('turma teste', treinador.Id, escola.Id);
        Contact aluno = TestDataFactory.criarAluno('Aluno', turma.Id);

        GradeHoraria__c grade = new GradeHoraria__c(
            DiaTreino__c='Terça-feira',
            NomeTurma__c=turma.Id,
            HoraInicio__c=Time.newInstance(0, 2, 2, 0));
        insert grade;
        

        Chamada__c chamada = new Chamada__c(
            Aluno__c=aluno.Id, 	
            Treinador__c=treinador.Id, 
            Turma__c=turma.Id,
            Status__c='Presente',
            Data__c=Date.newInstance(2022, 5, 17));
        insert chamada;
        
    }
    @IsTest
    static void presencaAlunosByTurmaTest(){
        Turma__c turma = [SELECT Id FROM Turma__c LIMIT 1];

        Test.startTest();
        List<porcentagemPresencaBO.AlunoTO> retorno = porcentagemPresencaController.presencaAlunosByTurma('Maio', '2022', turma.Id);
        Test.stopTest();

        System.assertEquals(1, retorno.size());
        System.assertEquals('aluno Aluno', retorno[0].nome);
    }
    @IsTest
    static void buscaDiasAulasTest(){
        Turma__c turma = [SELECT Id FROM Turma__c LIMIT 1];
        GradeHoraria__c grade = new GradeHoraria__c(
            DiaTreino__c='Segunda-feira',
            NomeTurma__c=turma.Id,
            HoraInicio__c=Time.newInstance(0, 2, 2, 0));
        insert grade;
        GradeHoraria__c grade1 = new GradeHoraria__c(
            DiaTreino__c='Quarta-feira',
            NomeTurma__c=turma.Id,
            HoraInicio__c=Time.newInstance(0, 2, 2, 0));
        insert grade1;
        GradeHoraria__c grade2 = new GradeHoraria__c(
            DiaTreino__c='Quinta-feira',
            NomeTurma__c=turma.Id,
            HoraInicio__c=Time.newInstance(0, 2, 2, 0));
        insert grade2;
        GradeHoraria__c grade4 = new GradeHoraria__c(
            DiaTreino__c='Sexta-feira',
            NomeTurma__c=turma.Id,
            HoraInicio__c=Time.newInstance(0, 2, 2, 0));
        insert grade4;
        GradeHoraria__c grade5 = new GradeHoraria__c(
            DiaTreino__c='Sábado',
            NomeTurma__c=turma.Id,
            HoraInicio__c=Time.newInstance(0, 2, 2, 0));
        insert grade5;
        GradeHoraria__c grade7 = new GradeHoraria__c(
            DiaTreino__c='Domingo',
            NomeTurma__c=turma.Id,
            HoraInicio__c=Time.newInstance(0, 2, 2, 0));
        insert grade7;


        Test.startTest();
        porcentagemPresencaBO.ListaTO retorno = porcentagemPresencaController.buscaDiasAulas('Maio', '2022', turma.Id);
        Test.stopTest();

        System.assertEquals(31, retorno.lista.size());
    }
    @IsTest
    static void buscaTotaisTest(){
        Turma__c turma = [SELECT Id FROM Turma__c LIMIT 1];

        Test.startTest();
        List<porcentagemPresencaBO.ListaTO> retorno = porcentagemPresencaController.buscaTotais('Maio', '2022', turma.Id);
        Test.stopTest();

        System.assertEquals(3, retorno.size());
        System.assertEquals('Total de presenças/dia', retorno[0].titulo);
        System.assertEquals('Total de faltas/dia', retorno[1].titulo);
        System.assertEquals('% de presença', retorno[2].titulo);
    }
}