force-app/main/default/objects/Chamada__c/Chamada__c.object-meta.xml
<CustomObject>
    <label>Chamada</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chamadas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Chamada__c/fields/Ano__c.field-meta.xml
<CustomField>
    <fullName>Ano__c</fullName>
    <label>Ano</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chamada__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Atestado</fullName>
            </value>
            <value>
                <fullName>Ausente</fullName>
            </value>
            <value>
                <fullName>Feriado</fullName>
            </value>
            <value>
                <fullName>Férias</fullName>
            </value>
            <value>
                <fullName>Folga</fullName>
            </value>
            <value>
                <fullName>Jogo</fullName>
            </value>
            <value>
                <fullName>Presente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Chamada__c/fields/Treinador__c.field-meta.xml
<CustomField>
    <fullName>Treinador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treinador</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Treinador/Tutor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Treinador</relationshipLabel>
    <relationshipName>Treinador</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chamada__c/fields/Turma__c.field-meta.xml
<CustomField>
    <fullName>Turma__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Turma</label>
    <referenceTo>Turma__c</referenceTo>
    <relationshipLabel>Chamadas</relationshipLabel>
    <relationshipName>Chamadas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GradeHoraria__c/GradeHoraria__c.object-meta.xml
<CustomObject>
    <label>Grade horária</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Grades horárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GradeHoraria__c/fields/DiaTreino__c.field-meta.xml
<CustomField>
    <fullName>DiaTreino__c</fullName>
    <label>Dia de treino</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Segunda-feira</fullName>
            </value>
            <value>
                <fullName>Terça-feira</fullName>
            </value>
            <value>
                <fullName>Quarta-feira</fullName>
            </value>
            <value>
                <fullName>Quinta-feira</fullName>
            </value>
            <value>
                <fullName>Sexta-feira</fullName>
            </value>
            <value>
                <fullName>Sábado</fullName>
            </value>
            <value>
                <fullName>Domingo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GradeHoraria__c/fields/NomeTurma__c.field-meta.xml
<CustomField>
    <fullName>NomeTurma__c</fullName>
    <label>Nome da turma</label>
    <referenceTo>Turma__c</referenceTo>
    <relationshipLabel>Grade horária</relationshipLabel>
    <relationshipName>GradesHorarias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Turma__c/Turma__c.object-meta.xml
<CustomObject>
    <label>Turma</label>
    <nameField>
        <label>Nome da Turma</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Turmas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Turma__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Equipe de transição</fullName>
            </value>
            <value>
                <fullName>Sub 11</fullName>
            </value>
            <value>
                <fullName>Sub 12</fullName>
            </value>
            <value>
                <fullName>Sub 13</fullName>
            </value>
            <value>
                <fullName>Sub 14</fullName>
            </value>
            <value>
                <fullName>Sub 15</fullName>
            </value>
            <value>
                <fullName>Sub 16</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Turma__c/fields/DiasTreino__c.field-meta.xml
<CustomField>
    <fullName>DiasTreino__c</fullName>
    <label>Dia(s) de treino</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Segunda-feira</fullName>
            </value>
            <value>
                <fullName>Terça-feira</fullName>
            </value>
            <value>
                <fullName>Quarta-feira</fullName>
            </value>
            <value>
                <fullName>Quinta-feira</fullName>
            </value>
            <value>
                <fullName>Sexta-feira</fullName>
            </value>
            <value>
                <fullName>Sábado</fullName>
            </value>
            <value>
                <fullName>Domingo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Turma__c/fields/NomeEscola__c.field-meta.xml
<CustomField>
    <fullName>NomeEscola__c</fullName>
    <label>Nome da escola</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Turmas</relationshipLabel>
    <relationshipName>Turmas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Turma__c/fields/SexoTurma__c.field-meta.xml
<CustomField>
    <fullName>SexoTurma__c</fullName>
    <label>Sexo da turma</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Masculino</fullName>
            </value>
            <value>
                <fullName>Feminino</fullName>
            </value>
            <value>
                <fullName>Mista</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Turma__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Turma__c/fields/Treinador__c.field-meta.xml
<CustomField>
    <fullName>Treinador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treinador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Turmas</relationshipLabel>
    <relationshipName>TreinadorTurma</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/turmaDAO.cls
public class turmaDAO {
    
    @AuraEnabled
    public static Turma__c buscarTurma(String Id){
      return[
        SELECT 
          Id, 
          NomeEscola__c,
          Name,
          SexoTurma__c,
          Status__c,
          Treinador__c,
          DiasTreino__c,
          Categoria__c,
          (SELECT Id, DiaTreino__c FROM GradesHorarias__r)
        FROM Turma__c
        WHERE Id = :Id
      ];
    }

    @AuraEnabled
    public static List<String> buscaDiasTreino(String recId){
      Set<String> diasTreinoSet = new Set<String>();

      for (GradeHoraria__c gradeHoraria : [SELECT Id, DiaTreino__c FROM GradeHoraria__c WHERE NomeTurma__c = :recId]) {
        diasTreinoSet.add(gradeHoraria.DiaTreino__c);
      }

      List<String> diasTreino = new List<String>(diasTreinoSet);
      return diasTreino;
    }

    public static List<Turma__c> buscarTurmasTreinador(Id pId){
      return [
        SELECT 
          Id,
          Name
        FROM
          Turma__c
        WHERE
          Treinador__c = :pId
      ];
    }

    public static List<Chamada__c> listaChamada(Date dataInicial, Date dataFinal, String turma){
      return[
        SELECT 
          Id, 
          Status__c, 
          Data__c
        FROM 
          Chamada__c 
        WHERE
          Data__c >: dataInicial AND 
          Data__c <: dataFinal AND
          Turma__c =: turma
        ORDER BY Data__c];
    }


    public static List<Contact> listaAlunos(String turma){
      return[
        SELECT 
          Id, 
          Ano__c, 
          Name, 
          (SELECT Id, Status__c FROM Chamadas__r) 
        FROM 
          Contact
        WHERE 
          Papel__c = 'Aluno' AND 
          Turma__c = :turma 
        ORDER BY Name];
    }
}