force-app/main/default/objects/PlanoAtividade__c/PlanoAtividade__c.object-meta.xml
<CustomObject>
    <label>Plano de Atividade</label>
    <nameField>
        <label>Nome de Plano de Atividade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planos de Atividades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanoAtividade__c/fields/Atividade__c.field-meta.xml
<CustomField>
    <fullName>Atividade__c</fullName>
    <label>Atividade</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PlanoAtividade__c/fields/PlanoTreino__c.field-meta.xml
<CustomField>
    <fullName>PlanoTreino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo lookup que retorna os Planos de Treinos disponiveis</description>
    <label>Plano de treino</label>
    <referenceTo>PlanoTreino__c</referenceTo>
    <relationshipLabel>Planos de Atividades</relationshipLabel>
    <relationshipName>Planos_de_Atividades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlanoAtividade__c/fields/TempoPlanejado__c.field-meta.xml
<CustomField>
    <fullName>TempoPlanejado__c</fullName>
    <label>Tempo planejado</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PlanoAtividade__c/fields/TempoRealizado__c.field-meta.xml
<CustomField>
    <fullName>TempoRealizado__c</fullName>
    <label>Tempo realizado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PlanoAtividade__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Campo picklist que contém o nome do tipo da atividade a ser realizada.</description>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desafios coordenativos</fullName>
            </value>
            <value>
                <fullName>Desafios técnico-táticos e socioemocionais</fullName>
            </value>
            <value>
                <fullName>Jogos de criatividade</fullName>
            </value>
            <value>
                <fullName>Jogos reduzidos e jogo formal</fullName>
            </value>
            <value>
                <fullName>Roda final</fullName>
            </value>
            <value>
                <fullName>Roda Inicial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PlanoTreino__c/PlanoTreino__c.object-meta.xml
<CustomObject>
    <label>Plano de treino</label>
    <nameField>
        <label>Nome de Plano de treino</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planos de treinos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PlanoAtividadeDAO.cls
public class PlanoAtividadeDAO {
    private static final PlanoAtividadeDAO instance = new PlanoAtividadeDAO();

    public static PlanoAtividadeDAO getInstance(){
        return instance;
    }

    public List<PlanoAtividade__c> getByPlanoTreino(Id idPlanoTreino){
        return [
            SELECT  
                Id,
                Atividade__c,
                PlanoTreino__c,
                TempoPlanejado__c,
                TempoRealizado__c,
                Tipo__c
            FROM 
                PlanoAtividade__c
            WHERE
                PlanoTreino__c = :idPlanoTreino
                
        ];
    }
}