force-app/main/default/objects/ConteudoAplicado__c/ConteudoAplicado__c.object-meta.xml
<CustomObject>
    <label>Conteúdo Aplicado</label>
    <nameField>
        <label>Nome de Conteúdo Aplicado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conteúdos Aplicados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ConteudoAplicado__c/fields/PlanoTreino__c.field-meta.xml
<CustomField>
    <fullName>PlanoTreino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de treino</label>
    <referenceTo>PlanoTreino__c</referenceTo>
    <relationshipLabel>Conteúdos Aplicados</relationshipLabel>
    <relationshipName>ConteudosAplicados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlanoTreino__c/PlanoTreino__c.object-meta.xml
<CustomObject>
    <label>Plano de treino</label>
    <nameField>
        <label>Nome de Plano de treino</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planos de treinos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanoTreino__c/fields/ConteudoAplicado__c.field-meta.xml
<CustomField>
    <fullName>ConteudoAplicado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conteúdo Aplicado</label>
    <referenceTo>ConteudoAplicado__c</referenceTo>
    <relationshipLabel>Planos de treinos</relationshipLabel>
    <relationshipName>PlanosTreinos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlanoTreino__c/fields/Objetivo__c.field-meta.xml
<CustomField>
    <fullName>Objetivo__c</fullName>
    <label>Objetivo</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PlanoTreino__c/fields/TipoTreino__c.field-meta.xml
<CustomField>
    <fullName>TipoTreino__c</fullName>
    <label>Tipo de treino</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quadra</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Psicologia</fullName>
            </value>
            <value>
                <fullName>Nutrição</fullName>
            </value>
            <value>
                <fullName>Reunião</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PlanoTreino__c/fields/Turma__c.field-meta.xml
<CustomField>
    <fullName>Turma__c</fullName>
    <label>Turma</label>
    <referenceTo>Turma__c</referenceTo>
    <relationshipLabel>Planos de treinos</relationshipLabel>
    <relationshipName>PlanosTreinos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Turma__c/Turma__c.object-meta.xml
<CustomObject>
    <label>Turma</label>
    <nameField>
        <label>Nome da Turma</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Turmas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PlanoTreinoDAO.cls
public class PlanoTreinoDAO {
    private static final PlanoTreinoDAO instance = new PlanoTreinoDAO();

    public static PlanoTreinoDAO getInstance(){
        return instance;
    }

    public PlanoTreino__c getById(Id pId){
        return [
            SELECT  
                Id,
                Data__c,
                ConteudoAplicado__c,
                Name,
                Objetivo__c,
                TipoTreino__c,
                Turma__c
            FROM 
                PlanoTreino__c
            WHERE
                Id = :pId
        ];
    }

    public List<PlanoTreino__c> getByDataAndTurma(Date dataPlano, Id idTurma){
        return [
            SELECT  
                Id,
                Data__c,
                ConteudoAplicado__c,
                Name,
                Objetivo__c,
                TipoTreino__c,
                Turma__c
            FROM 
                PlanoTreino__c
            WHERE
                Data__c = :dataPlano AND
                Turma__c = :idTurma
        ];
    }
}