force-app/main/default/objects/ConteudoAplicado__c/ConteudoAplicado__c.object-meta.xml
<CustomObject>
    <label>Conteúdo Aplicado</label>
    <nameField>
        <label>Nome de Conteúdo Aplicado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conteúdos Aplicados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ConteudoAplicado__c/fields/Dimensao__c.field-meta.xml
<CustomField>
    <fullName>Dimensao__c</fullName>
    <label>Dimensão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DESENVOLVIMENTO ESPORTIVO</fullName>
            </value>
            <value>
                <fullName>DESENVOLVIMENTO SOCIOEMOCIONAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConteudoAplicado__c/fields/Estrutura__c.field-meta.xml
<CustomField>
    <fullName>Estrutura__c</fullName>
    <label>Estrutura</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Dimensao__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1X0 COM BOLA - ATAQUE</fullName>
            </value>
            <value>
                <fullName>1X1 COM BOLA - ATAQUE</fullName>
            </value>
            <value>
                <fullName>1X1 NA BOLA - DEFESA</fullName>
            </value>
            <value>
                <fullName>2x2 COM BOLA - ATAQUE</fullName>
            </value>
            <value>
                <fullName>2x2 FORA DA BOLA - DEFESA</fullName>
            </value>
            <value>
                <fullName>2x2 SEM BOLA - ATAQUE</fullName>
            </value>
            <value>
                <fullName>3X3 FORA DA BOLA - DEFESA</fullName>
            </value>
            <value>
                <fullName>3X3 SEM BOLA - ATAQUE</fullName>
            </value>
            <value>
                <fullName>4X4 FORA DA BOLA - DEFESA</fullName>
            </value>
            <value>
                <fullName>4X4 SEM BOLA  ATAQUE</fullName>
            </value>
            <value>
                <fullName>JOGO FORMAL (5X5)  - ATAQUE</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConteudoAplicado__c/fields/PlanoTreino__c.field-meta.xml
<CustomField>
    <fullName>PlanoTreino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de treino</label>
    <referenceTo>PlanoTreino__c</referenceTo>
    <relationshipLabel>Conteúdos Aplicados</relationshipLabel>
    <relationshipName>ConteudosAplicados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConteudoAplicado__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Estrutura__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>TÁTICO</fullName>
            </value>
            <value>
                <fullName>TÉCNICO</fullName>
            </value>
            <value>
                <fullName>AMOR</fullName>
            </value>
            <value>
                <fullName>HUMILDADE</fullName>
            </value>
            <value>
                <fullName>DISCIPLINA</fullName>
            </value>
            <value>
                <fullName>CORAGEM</fullName>
            </value>
            <value>
                <fullName>TRABALHO EM EQUIPE</fullName>
            </value>
            <value>
                <fullName>SUPERAÇÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConteudoAplicado_Setting__mdt/ConteudoAplicado_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Conteúdo</label>
    <pluralLabel>Conteúdos</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConteudoAplicado_Setting__mdt/fields/ConteudoAplicado__c.field-meta.xml
<CustomField>
    <fullName>ConteudoAplicado__c</fullName>
    <label>Conteudo Aplicado</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Conteudos</relationshipLabel>
    <relationshipName>Conteudos</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ConteudoAplicado_Setting__mdt/fields/Dimensao__c.field-meta.xml
<CustomField>
    <fullName>Dimensao__c</fullName>
    <label>Dimensão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DESENVOLVIMENTO ESPORTIVO</fullName>
                <default>true</default>
                <label>DESENVOLVIMENTO ESPORTIVO</label>
            </value>
            <value>
                <fullName>DESENVOLVIMENTO SOCIOEMOCIONAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConteudoAplicado_Setting__mdt/fields/Estrutura__c.field-meta.xml
<CustomField>
    <fullName>Estrutura__c</fullName>
    <label>Estrutura</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1X0 COM BOLA - ATAQUE</fullName>
                <default>true</default>
                <label>1X0 COM BOLA - ATAQUE</label>
            </value>
            <value>
                <fullName>1X1 COM BOLA - ATAQUE</fullName>
            </value>
            <value>
                <fullName>1X1 NA BOLA - DEFESA</fullName>
            </value>
            <value>
                <fullName>2x2 COM BOLA - ATAQUE</fullName>
            </value>
            <value>
                <fullName>2x2 FORA DA BOLA - DEFESA</fullName>
            </value>
            <value>
                <fullName>2x2 SEM BOLA - ATAQUE</fullName>
            </value>
            <value>
                <fullName>3X3 FORA DA BOLA - DEFESA</fullName>
            </value>
            <value>
                <fullName>3X3 SEM BOLA - ATAQUE</fullName>
            </value>
            <value>
                <fullName>4X4 FORA DA BOLA - DEFESA</fullName>
            </value>
            <value>
                <fullName>4X4 SEM BOLA ATAQUE</fullName>
            </value>
            <value>
                <fullName>JOGO FORMAL (5X5) - ATAQUE</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConteudoAplicado_Setting__mdt/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
            <value>
                <fullName>TÁTICO</fullName>
            </value>
            <value>
                <fullName>TÉCNICO</fullName>
            </value>
            <value>
                <fullName>AMOR</fullName>
            </value>
            <value>
                <fullName>HUMILDADE</fullName>
            </value>
            <value>
                <fullName>DISCIPLINA</fullName>
            </value>
            <value>
                <fullName>CORAGEM</fullName>
            </value>
            <value>
                <fullName>TRABALHO EM EQUIPE</fullName>
            </value>
            <value>
                <fullName>SUPERAÇÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PlanoAtividade__c/PlanoAtividade__c.object-meta.xml
<CustomObject>
    <label>Plano de Atividade</label>
    <nameField>
        <label>Nome de Plano de Atividade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planos de Atividades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanoAtividade__c/fields/PlanoTreino__c.field-meta.xml
<CustomField>
    <fullName>PlanoTreino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo lookup que retorna os Planos de Treinos disponiveis</description>
    <label>Plano de treino</label>
    <referenceTo>PlanoTreino__c</referenceTo>
    <relationshipLabel>Planos de Atividades</relationshipLabel>
    <relationshipName>Planos_de_Atividades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlanoAtividade__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Campo picklist que contém o nome do tipo da atividade a ser realizada.</description>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desafios coordenativos</fullName>
            </value>
            <value>
                <fullName>Desafios técnico-táticos e socioemocionais</fullName>
            </value>
            <value>
                <fullName>Jogos de criatividade</fullName>
            </value>
            <value>
                <fullName>Jogos reduzidos e jogo formal</fullName>
            </value>
            <value>
                <fullName>Roda final</fullName>
            </value>
            <value>
                <fullName>Roda Inicial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PlanoTreino__c/PlanoTreino__c.object-meta.xml
<CustomObject>
    <label>Plano de treino</label>
    <nameField>
        <label>Nome de Plano de treino</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planos de treinos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanoTreino__c/fields/ConteudoAplicado__c.field-meta.xml
<CustomField>
    <fullName>ConteudoAplicado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conteúdo Aplicado</label>
    <referenceTo>ConteudoAplicado__c</referenceTo>
    <relationshipLabel>Planos de treinos</relationshipLabel>
    <relationshipName>PlanosTreinos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlanoTreino__c/fields/Objetivo__c.field-meta.xml
<CustomField>
    <fullName>Objetivo__c</fullName>
    <label>Objetivo</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PlanoTreino__c/fields/TipoTreino__c.field-meta.xml
<CustomField>
    <fullName>TipoTreino__c</fullName>
    <label>Tipo de treino</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quadra</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Psicologia</fullName>
            </value>
            <value>
                <fullName>Nutrição</fullName>
            </value>
            <value>
                <fullName>Reunião</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PlanoTreino__c/fields/Turma__c.field-meta.xml
<CustomField>
    <fullName>Turma__c</fullName>
    <label>Turma</label>
    <referenceTo>Turma__c</referenceTo>
    <relationshipLabel>Planos de treinos</relationshipLabel>
    <relationshipName>PlanosTreinos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PlanoTreinoBO.cls
public class PlanoTreinoBO {
    private static final PlanoTreinoBO instance = new PlanoTreinoBO();

    private PlanoTreinoBO() { }

    public static PlanoTreinoBO getInstance() {
        return instance;
    }

    public PlanoTreinoController.PlanoTreinoTO buscarPlanoTreino(String data, String idTurma){
        PlanoTreinoController.PlanoTreinoTO objPlanoTreinoTO = new PlanoTreinoController.PlanoTreinoTO();
        
        Date dataPlano = Date.valueOf(data);

        List<PlanoTreino__c> lstPlanoTreino = PlanoTreinoDAO.getInstance().getByDataAndTurma(dataPlano, Id.Valueof(idTurma));

        if(lstPlanoTreino.size() > 0){
            objPlanoTreinoTO.plano = new PlanoTreinoController.PlanoTO();
            objPlanoTreinoTO.plano.Id = lstPlanoTreino[0].Id;
            objPlanoTreinoTO.plano.Nome = lstPlanoTreino[0].Name;
            objPlanoTreinoTO.plano.DataPlano = data;
            objPlanoTreinoTO.plano.Objetivo = lstPlanoTreino[0].Objetivo__C;
            objPlanoTreinoTO.plano.Tipo = lstPlanoTreino[0].TipoTreino__c;
            objPlanoTreinoTO.plano.Turma = lstPlanoTreino[0].Turma__c;

            for (ConteudoAplicado__c item : ConteudoAplicadoDAO.getInstance().getByPlanoTreino(lstPlanoTreino[0].Id)) {
                PlanoTreinoController.ClassificacaoTO objClassificacao = new PlanoTreinoController.ClassificacaoTO();
                objClassificacao.Id = item.Id;
                objClassificacao.Dimensao = item.Dimensao__c;
                objClassificacao.Estrutura = item.Estrutura__c;
                objClassificacao.Tipo = item.Tipo__c;
                objClassificacao.Conteudo = item.Conteudo__c;
                objClassificacao.Complemento = item.ComplementoConteudo__c;

                objPlanoTreinoTO.classificacao.add(objClassificacao);
            }

            for (PlanoAtividade__c item : PlanoAtividadeDAO.getInstance().getByPlanoTreino(lstPlanoTreino[0].Id)) {
                PlanoTreinoController.PlanoAtividadeTO objPlanoAtividade = new PlanoTreinoController.PlanoAtividadeTO();
                objPlanoAtividade.Id = item.Id;
                objPlanoAtividade.Tipo = item.Tipo__c;
                objPlanoAtividade.TempoPlanejado = String.valueOf(item.TempoPlanejado__c);
                objPlanoAtividade.TempoRealizado = String.valueOf(item.TempoRealizado__c);
                objPlanoAtividade.Atividade = item.Atividade__c;

                objPlanoTreinoTO.atividade.add(objPlanoAtividade);
            }
        }
        return objPlanoTreinoTO;
    }
    
    public Boolean inserirPlanoTreino(PlanoTreinoController.PlanoTreinoTO planoTreino){
        Boolean retorno = false;
        
        try {
            PlanoTreino__c objPlanoTreino = new PlanoTreino__c(
                Id = planoTreino.Plano.Id == '' ? null : planoTreino.Plano.Id,
                TipoTreino__c = planoTreino.Plano.Tipo,
                Objetivo__c = planoTreino.Plano.Objetivo,
                Data__c = Date.valueof(planoTreino.Plano.DataPlano),
                Turma__c = planoTreino.Plano.Turma != null ? planoTreino.Plano.Turma : '',
                Name = planoTreino.Plano.Nome
            );

            upsert objPlanoTreino;

            List<ConteudoAplicado__c> lstConteudoAplicado = new List<ConteudoAplicado__c>();

            for (PlanoTreinoController.ClassificacaoTO item : planoTreino.classificacao) {
                if(!String.isBlank(item.Dimensao)){
                    ConteudoAplicado__c objConteudoAplicado = new ConteudoAplicado__c();
                    objConteudoAplicado.Id = item.Id;
                    objConteudoAplicado.PlanoTreino__c = objPlanoTreino.Id;
                    objConteudoAplicado.Dimensao__c = item.Dimensao;
                    objConteudoAplicado.Estrutura__c = item.Estrutura;
                    objConteudoAplicado.Tipo__c = item.Tipo;
                    objConteudoAplicado.Conteudo__c = item.Conteudo;
                    objConteudoAplicado.ComplementoConteudo__c = String.isBlank(item.Complemento) ? null : item.Complemento;

                    lstConteudoAplicado.add(objConteudoAplicado);
                }
            }

            upsert lstConteudoAplicado;

            List<PlanoAtividade__c> lstPlanoAtividade = new List<PlanoAtividade__c>();

            for (PlanoTreinoController.PlanoAtividadeTO item : planoTreino.atividade) {
                PlanoAtividade__c objPlanoAtividade = new PlanoAtividade__c();
                objPlanoAtividade.Id = item.Id;
                objPlanoAtividade.PlanoTreino__c = objPlanoTreino.Id;
                objPlanoAtividade.Tipo__c = item.Tipo;
                objPlanoAtividade.TempoPlanejado__c = String.isBlank(item.TempoPlanejado) ? null : Decimal.valueOf(item.TempoPlanejado);
                objPlanoAtividade.TempoRealizado__c = String.isBlank(item.TempoRealizado) ? null : Decimal.valueOf(item.TempoRealizado);
                objPlanoAtividade.Atividade__c = item.Atividade;

                lstPlanoAtividade.add(objPlanoAtividade);
            }

            upsert lstPlanoAtividade;

            retorno = true;
        } catch (Exception ex) {
            System.debug(ex.getMessage());
            retorno = false;
        }

        return retorno;
    }

    public List<String> buscarClassficicacao(String dimensao, String estrutura, String tipo){
        List<String> retorno = new List<String>();

        for (ConteudoAplicado_Setting__mdt item : ConteudoAplicadoDAO.getInstance().getClassificacao(dimensao, estrutura, tipo)) {
            if(!retorno.contains(item.Conteudo__c)){
                retorno.add(item.Conteudo__c);
            }
        }

        return retorno;
    }
}