force-app/main/default/objects/ConteudoAplicado__c/ConteudoAplicado__c.object-meta.xml
<CustomObject>
    <label>Conteúdo Aplicado</label>
    <nameField>
        <label>Nome de Conteúdo Aplicado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conteúdos Aplicados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ConteudoAplicado__c/fields/ComplementoConteudo__c.field-meta.xml
<CustomField>
    <fullName>ComplementoConteudo__c</fullName>
    <label>Complemento do Conteúdo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Conteudo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACOPLAMENTO SINCRONIA DE MOVIMENTOS</fullName>
            </value>
            <value>
                <fullName>ADAPTABILIDADE (PROBLEMAS MOTORES)</fullName>
            </value>
            <value>
                <fullName>ANTECIPAÇÃO</fullName>
            </value>
            <value>
                <fullName>ANTES DO DRIBLE</fullName>
            </value>
            <value>
                <fullName>ARREMESSAR, PENETRAR OU PASSAR / PASSAR E CORTAR (GIVE AND GO) / JOGO EM LARGURA E PROFUNDIDADE</fullName>
            </value>
            <value>
                <fullName>ARREMESSAR, PENETRAR OU PASSAR / PASSAR E CORTAR (GIVE AND GO) / JOGO EM LARGURA E PROFUNDIDADE - FINTAS DE PASSE</fullName>
            </value>
            <value>
                <fullName>ARREMESSAR, PENETRAR OU PASSAR / PASSAR E CORTAR (GIVE AND GO) / JOGO EM LARGURA E PROFUNDIDADE - OMBRO</fullName>
            </value>
            <value>
                <fullName>ARREMESSAR, PENETRAR OU PASSAR / PASSAR E CORTAR (GIVE AND GO) / JOGO EM LARGURA E PROFUNDIDADE - PEITO</fullName>
            </value>
            <value>
                <fullName>ARREMESSAR, PENETRAR OU PASSAR / PASSAR E CORTAR (GIVE AND GO) / JOGO EM LARGURA E PROFUNDIDADE - PICADO</fullName>
            </value>
            <value>
                <fullName>ARREMESSO SALTANDO</fullName>
            </value>
            <value>
                <fullName>BACKDOOR</fullName>
            </value>
            <value>
                <fullName>BANDEJA</fullName>
            </value>
            <value>
                <fullName>COSTAS</fullName>
            </value>
            <value>
                <fullName>DESLOCAR PARA RECEBER EM FUNÇÃO DO PASSE</fullName>
            </value>
            <value>
                <fullName>DIFERENCIAÇÃO (PRECISÃO E EFICIÊNCIA)</fullName>
            </value>
            <value>
                <fullName>DUPLOS</fullName>
            </value>
            <value>
                <fullName>DURANTE O DRIBLE</fullName>
            </value>
            <value>
                <fullName>EM L</fullName>
            </value>
            <value>
                <fullName>EM MOVIMENTO</fullName>
            </value>
            <value>
                <fullName>EM V</fullName>
            </value>
            <value>
                <fullName>EQUILIBRIO</fullName>
            </value>
            <value>
                <fullName>FINTA DE ARREMESSO</fullName>
            </value>
            <value>
                <fullName>FINTAS DE PASSE</fullName>
            </value>
            <value>
                <fullName>FLEXIBILIDADE</fullName>
            </value>
            <value>
                <fullName>FLUTUAR OU PRESSIONAR; JOGADOR-BOLA-CESTA</fullName>
            </value>
            <value>
                <fullName>FORÇA</fullName>
            </value>
            <value>
                <fullName>GIRO</fullName>
            </value>
            <value>
                <fullName>LATERAL</fullName>
            </value>
            <value>
                <fullName>MEMÓRIA</fullName>
            </value>
            <value>
                <fullName>OMBRO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConteudoAplicado__c/fields/Conteudo__c.field-meta.xml
<CustomField>
    <fullName>Conteudo__c</fullName>
    <label>Conteúdo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>5 ABERTOS</fullName>
            </value>
            <value>
                <fullName>AJUDA 1º LINHA</fullName>
            </value>
            <value>
                <fullName>AJUDA 2º LINHA</fullName>
            </value>
            <value>
                <fullName>AJUDAR O DEFENSOR BLOQUEADO</fullName>
            </value>
            <value>
                <fullName>ARREMESSAR</fullName>
            </value>
            <value>
                <fullName>ARREMESSAR PARADO OU EM MOVIMENTO</fullName>
            </value>
            <value>
                <fullName>AUTOCONFIANÇA</fullName>
            </value>
            <value>
                <fullName>AUTOCONTROLE</fullName>
            </value>
            <value>
                <fullName>AUTONOMIA</fullName>
            </value>
            <value>
                <fullName>BLOQUEAR ARREMESSO</fullName>
            </value>
            <value>
                <fullName>BLOQUEAR DEFENSOR FORA DA BOLA</fullName>
            </value>
            <value>
                <fullName>BLOQUEAR DEFENSOR NA BOLA</fullName>
            </value>
            <value>
                <fullName>CAPACIDADES FÍSICAS</fullName>
            </value>
            <value>
                <fullName>COMUNICAÇÃO</fullName>
            </value>
            <value>
                <fullName>CONSERVAR A POSSE DE BOLA</fullName>
            </value>
            <value>
                <fullName>CONTRA ATACAR EM &quot;TRAILER&quot;</fullName>
            </value>
            <value>
                <fullName>CONTRA-ATACAR EM CORREDORES</fullName>
            </value>
            <value>
                <fullName>CONTRA DEFESA INDIVIDUAL</fullName>
            </value>
            <value>
                <fullName>CONTRA DEFESA ZONA</fullName>
            </value>
            <value>
                <fullName>COOPERAÇÃO</fullName>
            </value>
            <value>
                <fullName>COORDENAÇÃO (CONTROLE DE CORPO E DE BOLA)</fullName>
            </value>
            <value>
                <fullName>CORTAR PARA RECEBER</fullName>
            </value>
            <value>
                <fullName>CRIAR LINHA DE PASSE</fullName>
            </value>
            <value>
                <fullName>CRUZAR</fullName>
            </value>
            <value>
                <fullName>DEFESA DE CORTES E TRIANGULO DEFENSIVO</fullName>
            </value>
            <value>
                <fullName>DESEQUILIBRAR A DEFESA</fullName>
            </value>
            <value>
                <fullName>DESLOCAMENTO POSICIONAMENTO E COMUNICAÇÃO</fullName>
            </value>
            <value>
                <fullName>DESLOCAMENTO POSICIONAMENTO LADO FORTE E LADO FRACO</fullName>
            </value>
            <value>
                <fullName>DESLOCAR PARA RECEBER EM FUNÇÃO DO DRIBLE</fullName>
            </value>
            <value>
                <fullName>DESLOCAR-SE INDUZINDO DIREÇÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConteudoAplicado_Setting__mdt/ConteudoAplicado_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Conteúdo</label>
    <pluralLabel>Conteúdos</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConteudoAplicado_Setting__mdt/fields/Conteudo__c.field-meta.xml
<CustomField>
    <fullName>Conteudo__c</fullName>
    <label>Conteúdo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5 ABERTOS</fullName>
                <default>true</default>
                <label>5 ABERTOS</label>
            </value>
            <value>
                <fullName>AJUDA 1º LINHA</fullName>
            </value>
            <value>
                <fullName>AJUDA 2º LINHA</fullName>
            </value>
            <value>
                <fullName>AJUDAR O DEFENSOR BLOQUEADO</fullName>
            </value>
            <value>
                <fullName>ARREMESSAR</fullName>
            </value>
            <value>
                <fullName>ARREMESSAR PARADO OU EM MOVIMENTO</fullName>
            </value>
            <value>
                <fullName>AUTOCONFIANÇA</fullName>
            </value>
            <value>
                <fullName>AUTOCONTROLE</fullName>
            </value>
            <value>
                <fullName>AUTONOMIA</fullName>
            </value>
            <value>
                <fullName>BLOQUEAR ARREMESSO</fullName>
            </value>
            <value>
                <fullName>BLOQUEAR DEFENSOR FORA DA BOLA</fullName>
            </value>
            <value>
                <fullName>BLOQUEAR DEFENSOR NA BOLA</fullName>
            </value>
            <value>
                <fullName>CAPACIDADES FÍSICAS</fullName>
            </value>
            <value>
                <fullName>COMUNICAÇÃO</fullName>
            </value>
            <value>
                <fullName>CONSERVAR A POSSE DE BOLA</fullName>
            </value>
            <value>
                <fullName>CONTRA ATACAR EM &quot;TRAILER&quot;</fullName>
            </value>
            <value>
                <fullName>CONTRA-ATACAR EM CORREDORES</fullName>
            </value>
            <value>
                <fullName>CONTRA DEFESA INDIVIDUAL</fullName>
            </value>
            <value>
                <fullName>CONTRA DEFESA ZONA</fullName>
            </value>
            <value>
                <fullName>COOPERAÇÃO</fullName>
            </value>
            <value>
                <fullName>COORDENAÇÃO (CONTROLE DE CORPO E DE BOLA)</fullName>
            </value>
            <value>
                <fullName>CORTAR PARA RECEBER</fullName>
            </value>
            <value>
                <fullName>CRIAR LINHA DE PASSE</fullName>
            </value>
            <value>
                <fullName>CRUZAR</fullName>
            </value>
            <value>
                <fullName>DEFESA DE CORTES E TRIANGULO DEFENSIVO</fullName>
            </value>
            <value>
                <fullName>DESEQUILIBRAR A DEFESA</fullName>
            </value>
            <value>
                <fullName>DESLOCAMENTO POSICIONAMENTO E COMUNICAÇÃO</fullName>
            </value>
            <value>
                <fullName>DESLOCAMENTO POSICIONAMENTO LADO FORTE E LADO FRACO</fullName>
            </value>
            <value>
                <fullName>DESLOCAR PARA RECEBER EM FUNÇÃO DO DRIBLE</fullName>
            </value>
            <value>
                <fullName>DESLOCAR-SE INDUZINDO DIREÇÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConteudoAplicado_Setting__mdt/fields/ConteudoAplicado__c.field-meta.xml
<CustomField>
    <fullName>ConteudoAplicado__c</fullName>
    <label>Conteudo Aplicado</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Conteudos</relationshipLabel>
    <relationshipName>Conteudos</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/PlanoTreino__c/PlanoTreino__c.object-meta.xml
<CustomObject>
    <label>Plano de treino</label>
    <nameField>
        <label>Nome de Plano de treino</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planos de treinos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanoTreino__c/fields/ConteudoAplicado__c.field-meta.xml
<CustomField>
    <fullName>ConteudoAplicado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conteúdo Aplicado</label>
    <referenceTo>ConteudoAplicado__c</referenceTo>
    <relationshipLabel>Planos de treinos</relationshipLabel>
    <relationshipName>PlanosTreinos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ConteudoAplicadoDAO.cls
public class ConteudoAplicadoDAO {
    private static final ConteudoAplicadoDAO instance = new ConteudoAplicadoDAO();

    public static ConteudoAplicadoDAO getInstance(){
        return instance;
    }

    public List<ConteudoAplicado__c> getByPlanoTreino(Id idPlanoTreino){
        return [
            SELECT  
                Id,
                Conteudo__c,
                ComplementoConteudo__c,
                Dimensao__c,
                Estrutura__c,
                Tipo__c
            FROM 
                ConteudoAplicado__c
            WHERE
                PlanoTreino__c = :idPlanoTreino
        ];
    }

    public List<ConteudoAplicado_Setting__mdt> getClassificacao(String dimensao, String estrutura, String tipo){
        return [
            SELECT  
                Conteudo__c,
                ConteudoAplicado__c,
                Dimensao__c,
                Estrutura__c,
                Tipo__c
            FROM 
                ConteudoAplicado_Setting__mdt
            WHERE
                Dimensao__c =: dimensao AND
                Estrutura__c =: estrutura AND
                Tipo__c =: tipo
        ];
    }
}