force-app/main/default/objects/ConteudoAplicado__c/ConteudoAplicado__c.object-meta.xml
<CustomObject>
    <label>Conteúdo Aplicado</label>
    <nameField>
        <label>Nome de Conteúdo Aplicado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conteúdos Aplicados</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ConteudoAplicado__c/fields/Conteudo__c.field-meta.xml
<CustomField>
    <fullName>Conteudo__c</fullName>
    <label>Conteúdo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>5 ABERTOS</fullName>
            </value>
            <value>
                <fullName>AJUDA 1º LINHA</fullName>
            </value>
            <value>
                <fullName>AJUDA 2º LINHA</fullName>
            </value>
            <value>
                <fullName>AJUDAR O DEFENSOR BLOQUEADO</fullName>
            </value>
            <value>
                <fullName>ARREMESSAR</fullName>
            </value>
            <value>
                <fullName>ARREMESSAR PARADO OU EM MOVIMENTO</fullName>
            </value>
            <value>
                <fullName>AUTOCONFIANÇA</fullName>
            </value>
            <value>
                <fullName>AUTOCONTROLE</fullName>
            </value>
            <value>
                <fullName>AUTONOMIA</fullName>
            </value>
            <value>
                <fullName>BLOQUEAR ARREMESSO</fullName>
            </value>
            <value>
                <fullName>BLOQUEAR DEFENSOR FORA DA BOLA</fullName>
            </value>
            <value>
                <fullName>BLOQUEAR DEFENSOR NA BOLA</fullName>
            </value>
            <value>
                <fullName>CAPACIDADES FÍSICAS</fullName>
            </value>
            <value>
                <fullName>COMUNICAÇÃO</fullName>
            </value>
            <value>
                <fullName>CONSERVAR A POSSE DE BOLA</fullName>
            </value>
            <value>
                <fullName>CONTRA ATACAR EM &quot;TRAILER&quot;</fullName>
            </value>
            <value>
                <fullName>CONTRA-ATACAR EM CORREDORES</fullName>
            </value>
            <value>
                <fullName>CONTRA DEFESA INDIVIDUAL</fullName>
            </value>
            <value>
                <fullName>CONTRA DEFESA ZONA</fullName>
            </value>
            <value>
                <fullName>COOPERAÇÃO</fullName>
            </value>
            <value>
                <fullName>COORDENAÇÃO (CONTROLE DE CORPO E DE BOLA)</fullName>
            </value>
            <value>
                <fullName>CORTAR PARA RECEBER</fullName>
            </value>
            <value>
                <fullName>CRIAR LINHA DE PASSE</fullName>
            </value>
            <value>
                <fullName>CRUZAR</fullName>
            </value>
            <value>
                <fullName>DEFESA DE CORTES E TRIANGULO DEFENSIVO</fullName>
            </value>
            <value>
                <fullName>DESEQUILIBRAR A DEFESA</fullName>
            </value>
            <value>
                <fullName>DESLOCAMENTO POSICIONAMENTO E COMUNICAÇÃO</fullName>
            </value>
            <value>
                <fullName>DESLOCAMENTO POSICIONAMENTO LADO FORTE E LADO FRACO</fullName>
            </value>
            <value>
                <fullName>DESLOCAR PARA RECEBER EM FUNÇÃO DO DRIBLE</fullName>
            </value>
            <value>
                <fullName>DESLOCAR-SE INDUZINDO DIREÇÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConteudoAplicado__c/fields/Dimensao__c.field-meta.xml
<CustomField>
    <fullName>Dimensao__c</fullName>
    <label>Dimensão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DESENVOLVIMENTO ESPORTIVO</fullName>
            </value>
            <value>
                <fullName>DESENVOLVIMENTO SOCIOEMOCIONAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConteudoAplicado__c/fields/Estrutura__c.field-meta.xml
<CustomField>
    <fullName>Estrutura__c</fullName>
    <label>Estrutura</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Dimensao__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1X0 COM BOLA - ATAQUE</fullName>
            </value>
            <value>
                <fullName>1X1 COM BOLA - ATAQUE</fullName>
            </value>
            <value>
                <fullName>1X1 NA BOLA - DEFESA</fullName>
            </value>
            <value>
                <fullName>2x2 COM BOLA - ATAQUE</fullName>
            </value>
            <value>
                <fullName>2x2 FORA DA BOLA - DEFESA</fullName>
            </value>
            <value>
                <fullName>2x2 SEM BOLA - ATAQUE</fullName>
            </value>
            <value>
                <fullName>3X3 FORA DA BOLA - DEFESA</fullName>
            </value>
            <value>
                <fullName>3X3 SEM BOLA - ATAQUE</fullName>
            </value>
            <value>
                <fullName>4X4 FORA DA BOLA - DEFESA</fullName>
            </value>
            <value>
                <fullName>4X4 SEM BOLA  ATAQUE</fullName>
            </value>
            <value>
                <fullName>JOGO FORMAL (5X5)  - ATAQUE</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConteudoAplicado__c/fields/PlanoTreino__c.field-meta.xml
<CustomField>
    <fullName>PlanoTreino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plano de treino</label>
    <referenceTo>PlanoTreino__c</referenceTo>
    <relationshipLabel>Conteúdos Aplicados</relationshipLabel>
    <relationshipName>ConteudosAplicados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConteudoAplicado__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Estrutura__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>TÁTICO</fullName>
            </value>
            <value>
                <fullName>TÉCNICO</fullName>
            </value>
            <value>
                <fullName>AMOR</fullName>
            </value>
            <value>
                <fullName>HUMILDADE</fullName>
            </value>
            <value>
                <fullName>DISCIPLINA</fullName>
            </value>
            <value>
                <fullName>CORAGEM</fullName>
            </value>
            <value>
                <fullName>TRABALHO EM EQUIPE</fullName>
            </value>
            <value>
                <fullName>SUPERAÇÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PlanoAtividade__c/PlanoAtividade__c.object-meta.xml
<CustomObject>
    <label>Plano de Atividade</label>
    <nameField>
        <label>Nome de Plano de Atividade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planos de Atividades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanoAtividade__c/fields/PlanoTreino__c.field-meta.xml
<CustomField>
    <fullName>PlanoTreino__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo lookup que retorna os Planos de Treinos disponiveis</description>
    <label>Plano de treino</label>
    <referenceTo>PlanoTreino__c</referenceTo>
    <relationshipLabel>Planos de Atividades</relationshipLabel>
    <relationshipName>Planos_de_Atividades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlanoAtividade__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Campo picklist que contém o nome do tipo da atividade a ser realizada.</description>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desafios coordenativos</fullName>
            </value>
            <value>
                <fullName>Desafios técnico-táticos e socioemocionais</fullName>
            </value>
            <value>
                <fullName>Jogos de criatividade</fullName>
            </value>
            <value>
                <fullName>Jogos reduzidos e jogo formal</fullName>
            </value>
            <value>
                <fullName>Roda final</fullName>
            </value>
            <value>
                <fullName>Roda Inicial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PlanoTreino__c/PlanoTreino__c.object-meta.xml
<CustomObject>
    <label>Plano de treino</label>
    <nameField>
        <label>Nome de Plano de treino</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Planos de treinos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanoTreino__c/fields/ConteudoAplicado__c.field-meta.xml
<CustomField>
    <fullName>ConteudoAplicado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conteúdo Aplicado</label>
    <referenceTo>ConteudoAplicado__c</referenceTo>
    <relationshipLabel>Planos de treinos</relationshipLabel>
    <relationshipName>PlanosTreinos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlanoTreino__c/fields/Objetivo__c.field-meta.xml
<CustomField>
    <fullName>Objetivo__c</fullName>
    <label>Objetivo</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PlanoTreino__c/fields/TipoTreino__c.field-meta.xml
<CustomField>
    <fullName>TipoTreino__c</fullName>
    <label>Tipo de treino</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quadra</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Psicologia</fullName>
            </value>
            <value>
                <fullName>Nutrição</fullName>
            </value>
            <value>
                <fullName>Reunião</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PlanoTreino__c/fields/Turma__c.field-meta.xml
<CustomField>
    <fullName>Turma__c</fullName>
    <label>Turma</label>
    <referenceTo>Turma__c</referenceTo>
    <relationshipLabel>Planos de treinos</relationshipLabel>
    <relationshipName>PlanosTreinos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Turma__c/Turma__c.object-meta.xml
<CustomObject>
    <label>Turma</label>
    <nameField>
        <label>Nome da Turma</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Turmas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Turma__c/fields/NomeEscola__c.field-meta.xml
<CustomField>
    <fullName>NomeEscola__c</fullName>
    <label>Nome da escola</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Turmas</relationshipLabel>
    <relationshipName>Turmas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Turma__c/fields/Treinador__c.field-meta.xml
<CustomField>
    <fullName>Treinador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Treinador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Turmas</relationshipLabel>
    <relationshipName>TreinadorTurma</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PlanoTreinoPDFController.cls
public with sharing class PlanoTreinoPDFController {
    public PlanoTreinoPDFController(ApexPages.StandardController sc) {
        Id idPlanoTreino = sc.getId();

        PlanoTreino__c objPlanoTreino = PlanoTreinoDAO.getInstance().getById(idPlanoTreino);

        objetivo = objPlanoTreino.Objetivo__c;
        tipoTreino = objPlanoTreino.TipoTreino__c;
        idPlanoTreino = objPlanoTreino.Id;
        nomePlano = objPlanoTreino.Name;
        dataPlano = objPlanoTreino.Data__c.day() + '/' + objPlanoTreino.Data__c.month() + '/' + objPlanoTreino.Data__c.year();

        Turma__c objTurma = turmaDAO.buscarTurma(objPlanoTreino.Turma__c);
        escola = AccountDAO.getInstance().getById(objTurma.NomeEscola__c).Name;
        treinador = contactDAO.getById(objTurma.Treinador__c).Name;

        planoTreino = new PlanoTreinoController.PlanoTreinoTO();
        for (ConteudoAplicado__c objConteudoAplicado : ConteudoAplicadoDAO.getInstance().getByPlanoTreino(idPlanoTreino)) {
            PlanoTreinoController.ClassificacaoTO objClassificacao = new PlanoTreinoController.ClassificacaoTO();
            objClassificacao.Estrutura = objConteudoAplicado.Estrutura__c;
            objClassificacao.Dimensao = objConteudoAplicado.Dimensao__c;
            objClassificacao.Tipo = objConteudoAplicado.Tipo__c;
            objClassificacao.Conteudo = objConteudoAplicado.Conteudo__c;
            objClassificacao.Complemento = objConteudoAplicado.ComplementoConteudo__c == null ? 'N/A' : objConteudoAplicado.ComplementoConteudo__c;

            planoTreino.classificacao.add(objClassificacao);
        }

        for (PlanoAtividade__C objPlanoAtividade : PlanoAtividadeDAO.getInstance().getByPlanoTreino(idPlanoTreino)) {
            PlanoTreinoController.PlanoAtividadeTO objPlanoAtividadeTO = new PlanoTreinoController.PlanoAtividadeTO();
            objPlanoAtividadeTO.Atividade = objPlanoAtividade.Atividade__c;
            objPlanoAtividadeTO.TempoPlanejado = String.valueOf(objPlanoAtividade.TempoPlanejado__c);
            objPlanoAtividadeTO.TempoRealizado = String.valueOf(objPlanoAtividade.TempoRealizado__c);
            objPlanoAtividadeTO.Tipo = objPlanoAtividade.Tipo__c;

            planoTreino.atividade.add(objPlanoAtividadeTO);
        }


    }

    public PlanoTreinoPDFController() {
        // Id idTurma = Id.valueOf(ApexPages.currentPage().getParameters().get('id'));
        // Id idPlanoTreino;

        // String day = ApexPages.currentPage().getParameters().get('data').subString(0,2);
        // String month = ApexPages.currentPage().getParameters().get('data').subString(2,4);
        // String year = ApexPages.currentPage().getParameters().get('data').subString(4,8);

        // dataPlano = day + '/' + month + '/' + year;
        // Date data = Date.parse(dataPlano);

        // List<PlanoTreino__c> lstPlanoTreino = PlanoTreinoDAO.getInstance().getByDataAndTurma(data, idTurma);

        // for (PlanoTreino__c objPlanoTreino : lstPlanoTreino) {
        //     objetivo = objPlanoTreino.Objetivo__c;
        //     tipoTreino = objPlanoTreino.TipoTreino__c;
        //     idPlanoTreino = objPlanoTreino.Id;
        //     nomePlano = objPlanoTreino.Name;
        // }

        // Turma__c objTurma = turmaDAO.buscarTurma(idTurma);
        // escola = AccountDAO.getInstance().getById(objTurma.NomeEscola__c).Name;
        // treinador = contactDAO.getById(objTurma.Treinador__c).Name;

        // planoTreino = new PlanoTreinoController.PlanoTreinoTO();
        // for (ConteudoAplicado__c objConteudoAplicado : ConteudoAplicadoDAO.getInstance().getByPlanoTreino(idPlanoTreino)) {
        //     PlanoTreinoController.ClassificacaoTO objClassificacao = new PlanoTreinoController.ClassificacaoTO();
        //     objClassificacao.Estrutura = objConteudoAplicado.Estrutura__c;
        //     objClassificacao.Dimensao = objConteudoAplicado.Dimensao__c;
        //     objClassificacao.Tipo = objConteudoAplicado.Tipo__c;
        //     objClassificacao.Conteudo = objConteudoAplicado.Conteudo__c;
        //     objClassificacao.Complemento = objConteudoAplicado.ComplementoConteudo__c == null ? 'N/A' : objConteudoAplicado.ComplementoConteudo__c;

        //     planoTreino.classificacao.add(objClassificacao);
        // }

        // for (PlanoAtividade__C objPlanoAtividade : PlanoAtividadeDAO.getInstance().getByPlanoTreino(idPlanoTreino)) {
        //     PlanoTreinoController.PlanoAtividadeTO objPlanoAtividadeTO = new PlanoTreinoController.PlanoAtividadeTO();
        //     objPlanoAtividadeTO.Atividade = objPlanoAtividade.Atividade__c;
        //     objPlanoAtividadeTO.TempoPlanejado = String.valueOf(objPlanoAtividade.TempoPlanejado__c);
        //     objPlanoAtividadeTO.TempoRealizado = String.valueOf(objPlanoAtividade.TempoRealizado__c);
        //     objPlanoAtividadeTO.Tipo = objPlanoAtividade.Tipo__c;

        //     planoTreino.atividade.add(objPlanoAtividadeTO);
        // }
    }

    public String dataPlano{get; set;}
    public String objetivo{get; set;}
    public String tipoTreino{get; set;}
    public String escola{get; set;}
    public String treinador{get; set;}
    public String nomePlano{get; set;}
    public PlanoTreinoController.PlanoTreinoTO planoTreino{get; set;}
}